language: csharp
solution: src/SparkPost.sln
matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore src/SparkPost.sln
  - dotnet restore src/SparkPost.Dotnet
script:
  - xbuild /p:Configuration=Release src/SparkPost.sln
  - nunit-console src/SparkPost.Tests/bin/Release/SparkPost.Tests.dll
